fix potential arrary overflow problem of _recvBuffer
arduino-libraries/ArduinoBLE pull request #214
Opened 2021-12-17 11:29 UTC by bigbearishappy

I find that when I use my nano 33 ble with this BLE lib.
Sometimes when I use the demo project ScanCallback.ino,
my program freezes because of the overflow of _recvBuffer.

2021-12-17 11:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/ArduinoBLE?pullRequest=214) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/ArduinoBLE?pullRequest=214) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/ArduinoBLE?pullRequest=214) it.</sub>

2021-12-20 05:45 UTC, aentinger requested changes
Looking alright, however a couple of questions remain ...

2021-12-20 05:45 UTC, aentinger commented on src/utility/HCI.cpp
> +	if (sizeof(_recvBuffer) <= _recvIndex)
```suggestion
	if (_recvIndex >= sizeof(_recvBuffer))
```
Since the size of the _recvBuffer is constant this is much easier to read ...

2021-12-20 05:45 UTC, aentinger commented on src/utility/HCI.cpp
> +			_debug->println("_recvBuffer overflow");
A bit of much indentation here, have you been using tabs instead of spaces?

2021-12-20 05:45 UTC, aentinger commented on src/utility/HCI.cpp
> +	  continue;
Why this statement here? Since you are resetting `_recvIndex` to zero you can write to `_recvBuffer` without any overflow.

2021-12-21 09:51 UTC, bigbearishappy commented on src/utility/HCI.cpp
> +			_debug->println("_recvBuffer overflow");
Oh, sorry.I used the tab.

2021-12-21 09:53 UTC, bigbearishappy commented on src/utility/HCI.cpp
> +	  continue;
Yes, you are right. No need to add this code here.

2021-12-22 05:24 UTC, aentinger reviewed
LGTM, however you could have left the debug message. (Possibly reinsert it?) I was just critical of the indentation, which seemed too much to me.

2021-12-22 05:43 UTC, bigbearishappy commented
> LGTM, however you could have left the debug message. (Possibly reinsert it?) I was just critical of the indentation, which seemed too much to me.

Thank you for your reply.It seems that it's better to keep the debug msg.I just restore the code of it.I agree with your suggestion to delete the "continue;".

2021-12-22 05:52 UTC, aentinger approved these changes
Thank you @bigbearishappy :rocket:

2021-12-22 05:52 UTC, merged